### ISSUE TITLE
Receivers' properties to be monitored

### ISSUE THREAD

**Issue by jjpopski** [marco-buttu/suricate#55]
Some receivers'  property if monitored could give more infos about the health state of the system. About the  SRT  K-Band MF Recivers, these could be added to srt.yaml.  

<vdL1 description="drain voltage for the LNA left channel, stage 1"    />
<vdR1 description="drain voltage for the LNA right channel, stage 1"   />
<vdL2 description="drain voltage for the LNA left channel, stage 2"    />
<vdR2 description="drain voltage for the LNA right channel, stage 2"  />
<vdL3 description="drain voltage for the LNA left channel, stage 3"    />
<vdR3 description="drain voltage for the LNA right channel, stage 3" />
<vdL4 description="drain voltage for the LNA left channel, stage 4"   />
<vdR4 description="drain voltage for the LNA right channel, stage 4"    />
 <vdL5 description="drain voltage for the LNA left channel, stage 5" />
<vdR5 description="drain voltage for the LNA right channel, stage 5"   />
<idL1 description="drain current for the LNA left channel, stage 1"   />
<idR1 description="drain current for the LNA right channel, stage 1"    />
<idL2 description="drain current for the LNA left channel, stage 2"   />
<idR2 description="drain current for the LNA right channel, stage 2" />
<idL3 description="drain current for the LNA left channel, stage 3" />
<idR3 description="drain current for the LNA right channel, stage 3"    />
<idL4 description="drain current for the LNA left channel, stage 4"    />
<idR4 description="drain current for the LNA right channel, stage 4"    />
<idL5 description="drain current for the LNA left channel, stage 5"/>
<idR5 description="drain current for the LNA right channel, stage     />
<vgL1 description="gate voltage for the LNA left channel, stage 1"    />
<vgR1 description="gate voltage for the LNA right channel, stage 1    />
<vgL2 description="gate voltage for the LNA left channel, stage 2"/>
<vgR2 description="gate voltage for the LNA right channel, stage 2" />
<vgL3 description="gate voltage for the LNA left channel, stage 3"   />
<vgR3 description="gate voltage for the LNA right channel, stage 3"/>
<vgL4 description="gate voltage for the LNA left channel, stage 4"    />
<vgR4 description="gate voltage for the LNA right channel, stage     />
<vgL5 description="gate voltage for the LNA left channel, stage 5"    />
<vgR5 description="gate voltage for the LNA right channel, stage 5"    />

**Comment by marco-buttu** [comment]
Related to issue #45 .

**Comment by marco-buttu** [comment]
Fixed in commit 30df556. See [srt.yaml](https://github.com/marco-buttu/suricate/blob/master/templates/srt.yaml).
