### ISSUE TITLE
Jlog error flooding if a component is down

### ISSUE THREAD

**Issue by jjpopski** [marco-buttu/suricate#61]
If a component is down, jlog shows errors due to catched exceptions. The system keeps running, though. 

![image](https://user-images.githubusercontent.com/10814075/70825209-33fa1d80-1de4-11ea-8820-39fc91d2de6f.png)

**Comment by marco-buttu** [comment]
Nothing to fix from the suricate side. Currently you can `sudo service suricate-server stop`, remove the component from the configuration file and restart `suricate-server` again. You can also slow down the component request by a configuration parameter (`RESCHEDULE_ERROR_INTERVAL`). In the future the compnent can be removed in real time from the monitored ones (by sending a SET HTTP request).
